deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: java-app
        path: java-app


    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v3
      with:
        app-name: exedemo
        slot-name: production
        package:

