name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Dùng Temurin thay vì Microsoft JDK
          java-version: '17'

      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: false
          cache-default-branch-only: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_727643565 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
